### ISSUE TITLE
Search showing duplicates

### ISSUE THREAD

**Issue by GetAwayCoxn** [ThornyFFXI/FindAll#1]
I apologize I do not have a lot of information here for replication but I was on a mule, I did /fa search Jhakri* and got results (from two other chars, not the one i was searching from in case that matters), and it was showing weird duplicates of items that you can only have one of? I suppose you could have 2 of these ambu pieces if you mistakenly had one in porter slip and one in your inventory as well, but not 3?
![JhakriSearch](https://user-images.githubusercontent.com/66495755/151710235-208a7f22-3c49-4c57-ab8d-df85a6b55a67.PNG)

**Comment by GetAwayCoxn** [comment]
The really strange thing is I did a couple more searches for other items just to see what would happen and those worked as expected. I redid the original /fa search Jhakri* and it worked fine the second time. I didnt zone or change characters or anything like that in between and I don't know if it matters but the original search that gave me the weird results was not only the first search of the day/login but quite possibly the first time I have searched for anything on that char.

**Comment by ThornyFFXI** [comment]
Only thing that comes to mind is that it somehow parsed the same binary file multiple times.  The fact it happened for each character and was off by the same scale (things you didn't have still showed 0) supports that.  I don't have an immediate solution, but I'll leave the issue open and review the code for possible causes.

**Comment by ThornyFFXI** [comment]
Fixed in 1.06.
