### ISSUE TITLE
ability to see item and KI in same search

### ISSUE THREAD

**Issue by TeoTwawki** [ThornyFFXI/FindAll#4]
Hey Thorny. While I really appreciate the attempt to make it a setting, Would it be possible to make having the prefix off simply show both in a single search? Because right now it takes flipping it back and forth constantly if you want to check items and key items (pls ignore that both search's were for "prism" this was only done because I knew I had both items and keyitems that would be found by that search term):
![2023 02 15_172535](https://user-images.githubusercontent.com/6871475/219202405-79191619-5be2-4e70-9d75-b47162dbe76e.png)

Since there is a limit to how many things display, regular items could be prioritized, and the prefix could sill be used to show -only- ki's as it already does. KI could be treated as if it were another container text wise: `Found a prismatic fragment in Playername's Keyitems`

**Comment by ThornyFFXI** [comment]
I don't see a reason to treat it as it's own container.  The message is already unique, it does not specify a container at all.

Allowing the ki prefix to still be used is a good idea, I will do that in next update and add an item prefix as well.

**Comment by ThornyFFXI** [comment]
Intended behavior when KeyItemPrefix is disabled is to show both key items and items for all results.  If this is not the case, it will be verified and corrected in the morning.

**Comment by TeoTwawki** [comment]
> I don't see a reason to treat it as it's own container. The message is already unique, it does not specify a container at all.
> 
> Allowing the ki prefix to still be used is a good idea, I will do that in next update and add an item prefix as well.

I only meant for the message text purposes. I gave an example. The current message in the screenshot just says "found on"

> Intended behavior when KeyItemPrefix is disabled is to show both key items and items for all results. If this is not the case, it will be verified and corrected in the morning.

ok, thanks.

**Comment by ThornyFFXI** [comment]
```I only meant for the message text purposes. I gave an example. The current message in the screenshot just says "found on"```

It says 'found on Character'.  Is there a reason that's not an adequate message?  Key items are not in any specific bag, why would it need a pseudo-bag?

**Comment by ThornyFFXI** [comment]
The reason your prism powders were not displaying is because the item search logic will only append wildcards at start/end if no search results are found without them.  Because your key item search found items by appending wildcards, the item search did not see the results as empty and append wildcards.  A search for `prism*` or `*prism*` would have worked correctly.  I have altered this behavior in 1.15, so that items will append wildcards if no items are found *and* key items will append wildcards if no key items are found.  This should produce the behavior you were hoping for.

I have also added the ability to use item: or ki: prefixes regardless of whether keyitemprefix is enabled.

**Comment by TeoTwawki** [comment]
> It says 'found on Character'. Is there a reason that's not an adequate message? Key items are not in any specific bag, why would it need a pseudo-bag?

The message for items in main inventory says "on playername" the same way, but I just now realized it -only- does that for multiples and not singular, which KI always are so it is different and I was wrong. I felt specifying it is a KI in some way in that message was clearer. ¯\\\_(ツ)\_/¯
![image](https://user-images.githubusercontent.com/6871475/219702683-2c0413f1-d702-4003-9614-82e106108d26.png)

**Comment by TeoTwawki** [comment]
> The reason your prism powders were not displaying is because the item search logic will only append wildcards at start/end if no search results are found without them. Because your key item search found items by appending wildcards, the item search did not see the results as empty and append wildcards. A search for `prism*` or `*prism*` would have worked correctly. I have altered this behavior in 1.15, so that items will append wildcards if no items are found _and_ key items will append wildcards if no key items are found. This should produce the behavior you were hoping for.
> 
> I have also added the ability to use item: or ki: prefixes regardless of whether keyitemprefix is enabled.

ahhh that makes sense. Ty for the tweakage :+1:
