### ISSUE TITLE
extra line with chatlog output

### ISSUE THREAD

**Issue by gilles007-** [ThornyFFXI/FindAll#6]
when i use : `/findall tricolored` with chatlog mode, i got this :
`[FindAll] Found 12 tricolored carps in character's case.`
`[FindAll] Found a tricolored carp in character's case.`
i consider this second line as a duplicate
is it possible to correct this ?

**Comment by ThornyFFXI** [comment]
Yes, I will look into it in the morning.

**Comment by ThornyFFXI** [comment]
Should be fixed in 1.16.
